// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtDWPWDQj5FKOzIIuPER4As_ZK1RUV2sk',
    appId: '1:550869134722:web:ac2f59e0054a74f3fd339b',
    messagingSenderId: '550869134722',
    projectId: 'lab10app-67622',
    authDomain: 'lab10app-67622.firebaseapp.com',
    storageBucket: 'lab10app-67622.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd--m4LGbV_Pyzy0Ymm9uHb3zyRnssiAM',
    appId: '1:550869134722:android:7001543b770da42dfd339b',
    messagingSenderId: '550869134722',
    projectId: 'lab10app-67622',
    storageBucket: 'lab10app-67622.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsYZO4ff-WFNegZn5wLfzGD-mB2iK37c4',
    appId: '1:550869134722:ios:965a41c6282a2d82fd339b',
    messagingSenderId: '550869134722',
    projectId: 'lab10app-67622',
    storageBucket: 'lab10app-67622.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
